<?php

function pet_menu() {
    $names = array('Charlie', 'Crow');
    $items = array();
    foreach($names as $name) {
        $items['pet/' . $name] = array(
            'title' => $name,
            'page callback' => 'pet_display',
            'page arguments' => array(1, $name),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
    };
    return $items;
}

function pet_display($pet_name) {
    return '
    <h2>This is ' . $pet_name . '!</h2>
    <img class="img-responsive img-rounded" src="/sites/all/modules/pet/images/' . $pet_name . '.jpg" alt="my pet">
    <p>' . $pet_name . ' is a demon cat.</p>
    ';
}
