<?php

function rockpaperscissors_menu() {
    $items['rock paper scissors'] = array(
        'title' => 'Rock Paper Scissors',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rockpaperscissors_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['rockpaperscissors_player2_page'] = array(
        'title' => 'Player 2 choose your move',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rockpaperscissors_form'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['rockpaperscissors_success_page'] = array(
        'title' => 'Results',
        'page callback' => 'rockpaperscissors_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function rockpaperscissors_form() {
    $form['player_move'] = array(
        '#title' => 'Rock, Paper, or Scissors?',
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_move'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Done',
    );

    return $form;
}

function element_validate_move($element) {
    $words = array('rock', 'paper', 'scissors');

    $move = strtolower($element['#value']);
    $move = trim($move);

    if (!in_array($move, $words)) {
        form_error($element, t('Enter Valid Move'));
    }
}

function rockpaperscissors_form_submit($form, &$form_state) {
    $player_move = $form_state['values']['player_move'];

    $player_move = strtolower($player_move);
    $player_move = trim($player_move);

    if (!$_SESSION['player1']) {
        $_SESSION['player1'] = $player_move;
        $form_state['redirect'] = "rockpaperscissors_player2_page";
    } else {
        $_SESSION['player2'] = $player_move;
        $form_state['redirect'] = "rockpaperscissors_success_page";
    }
}

function rockpaperscissors_success() {
    $player_one = $_SESSION['player1'];
    $player_two = $_SESSION['player2'];

    // echo '<pre>';
    // var_dump($_SESSION['player1']);
    // var_dump($_SESSION['player2']);
    // echo '</pre>';
    // exit;


    if ($player_one == $player_two) {
        $_SESSION['player1'] = null;
        $_SESSION['player2'] = null;
        return "Draw!";
    } elseif ($player_one == "rock" && $player_two == "scissors" || $player_one == "scissors" && $player_two == "paper" || $player_one == "paper" && $player_two == "rock") {
        $_SESSION['player1'] = null;
        $_SESSION['player2'] = null;
        return "Player 1 Wins!";
    } else {
        $_SESSION['player1'] = null;
        $_SESSION['player2'] = null;
        return "Player 2 Wins!";
    }
}
