<?php

function greeting_menu() {
    $items = array();
    $items['hello_friend'] = array(
        'title' => 'Hello Friend!',
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['farewell'] = array(
        'title' => 'Farewell Friend!',
        'page callback' => 'say_farewell',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function say_hello() {
    return '<p>Hello!</p>';
}

function say_farewell() {
    return '<p>Farewell</p>';
}

function greeting_user_login(&$edit, $account) {

    // Use the Below to Check Contents of $account or $edit
    // echo '<pre>';
    // var_dump($edit);
    // echo '</pre>';
    // exit;

    $_GET['destination'] = 'hello_friend';
}

function greeting_user_logout() {
    $_GET['destination'] = 'farewell';
}
