<?php

function greeting_menu() {
    $items = array();
    $items['hello_friend'] = array(
        'title' => 'Hello Friend!',
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['farewell'] = array(
        'title' => 'Farewell Friend!',
        'page callback' => 'say_farewell',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function say_hello() {
    return '<p>Hello!</p>';
}

function say_farewell() {
    return '<p>Farewell</p>';
}

function greeting_user_login(&$edit, $account) {

    // Use the Below to Check Contents of $account or $edit
    // echo '<pre>';
    // if (isset($account->roles[3])) {
    //     echo 'is administrator';
    // } else if (isset($account->roles[2])) {
    //     echo 'is authenticated';
    // }
    // echo '</pre>';
    // exit;

    if (isset($account->roles[3])) {
        drupal_set_message('Welcome to the Admin View!');
    } else {
        drupal_set_message('Nice to see you!');
    }

    // $_GET['destination'] = 'hello_friend';
}

function greeting_user_logout($account) {

    // echo '<pre>';
    // var_dump($account);
    // echo '</pre>';
    // exit;

// Currently Does Not Work
    if (isset($account->roles[3])) {
        drupal_set_message('Bye bye bye!');
    } else {
        drupal_set_message('Come back soon!');
    }

    // $_GET['destination'] = 'farewell';
}
