<?php

function coffeenews_menu() {
    $items['path-to-ajax/%/%'] = array(
        'access arguments' => array('access content'),
        'page callback' => 'coffeenews_ajax_callback',
        'page arguments' => array(1,2),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function coffeenews_ajax_callback($js, $node_id) {
    $node = node_load($node_id);



    if ($js == 'nojs') {
        drupal_goto('node/' . $node->nid);
    }

    $build = node_view($node);
    $html = render($build);

    $commands = array();
    $commands[] = ajax_command_html('#coffeenews-ajax-wrapper', $html);
    echo "<pre>";
    var_dump($commands);
    echo "<pre>";
    exit;

    print ajax_render($commands);
    exit;

}
